kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: litecoin
  labels:
    type: local
spec:
  storageClassName: "gp2"
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: Service
metadata: 
  name: litecoin
spec:
  selector:
    app: litecoin
    component: daemon
    version: '0.18.1'
  ports:
    - protocol: TCP
      port: 9333
      targetPort: 9333
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
  labels: &litecoin-labels
    app: litecoin
    component: daemon
    version: '0.18.1'
spec:
  selector:
    matchLabels: *litecoin-labels
  serviceName: litecoin
  replicas: 1
  template:
    metadata:
      labels: *litecoin-labels
    spec:
      containers:
        - name: litcoin
          image: adisharma96/lite-test:v2
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 250Mi
  volumeClaimTemplates:
    - metadata:
        name: litecoin-data
      spec:
        storageClassName: "gp2"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 256Mi
